branch-defaults:
  main:
    environment: udagram-api-dev

environment-defaults:
  udagram-api-dev:
    branch: null
    repository: null

global:
  application_name: udagram-api
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-1
  profile: null
  sc: git
